$schema: https://azuremlschemas.azureedge.net/latest/schedule.schema.json
name: weekly_qa_retrain
trigger:
  type: cron
  expression: "0 1 * * *"     # Every day at 1:00 AM 
create_job: ./train-pipeline.yml