$schema: https://azuremlschemas.azureedge.net/latest/schedule.schema.json
name: weekly_qa_retrain
trigger:
  type: cron
  expression: "*/10 * * * *"     # Every 10 minutes for testing
create_job: 
  type: pipeline
  pipeline: ./train-pipeline.yml