$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
name: test-command-job
command: |
  echo "hello world"
  python train.py --training_data ${{inputs.training_data}} --n_estimators ${{inputs.n_estimators}}
code: ../src
environment: 
  image: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
  conda_file: ../environment/conda.yml
compute: azureml:CASH-CLEARING-COMPUTE-CLUSTER
experiment_name: test-experiment
description: A simple command job
inputs:
  training_data: 
    type: uri_file
    path: azureml:qa-dataset@latest
  n_estimators: 100