$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: |
  echo "hello world"
  pip install -r requirements.txt
  python train.py --training_data ${{inputs.training_data}} --n_estimators ${{inputs.n_estimators}}
code: ../src
environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
compute: azureml:CASH-CLEARING-COMPUTE-CLUSTER
experiment_name: test-experiment
description: A simple command job
inputs:
  training_data: 
    type: uri_file
    path: azureml:qa-dataset@latest
  n_estimators: 100