$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: ../src
command: >-
  python train.py 
  --training_data ${{inputs.training_data}} 
  --n_estimators ${{inputs.n_estimators}}
inputs:
  training_data: 
    type: uri_file
    path: azureml:qa-dataset@latest
  n_estimators: 100
environment: 
  build:
    path: ../environment
compute: azureml:CASH-CLEARING-COMPUTE-CLUSTER
display_name: qa-training-run
experiment_name: quality-assurance