$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: |
  echo "hello world"
  python train.py --training_data ${{inputs.training_data}} --n_estimators ${{inputs.n_estimators}}
code: ../src
environment: azureml:AzureML-frap-sklearn-1.0-ubuntu20.04-py38-cpu:latest
compute: azureml:CASH-CLEARING-COMPUTE-CLUSTER
experiment_name: test-experiment
description: A simple command job
inputs:
  training_data: 
    type: uri_file
    path: azureml:qa-dataset@latest
  n_estimators: 100