name: aml-qa-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip:
    - azureml-mlflow
    - scikit-learn
    - pandas
    - mlflow
    - python-dateutil
    - azure-identity
    - azure-keyvault-secrets