name: btp-check
on: workflow_dispatch

jobs:
  btp-check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
  
      - name: Check brew version and install a package
        run: |
          brew --version # This will now work
          brew install --cask btp
      
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Copy file file to temp folder
        run: |
          mkdir -p temp_dir
          cp ./btp-cli-linux-amd64-2.97.0.tar.gz temp_dir/

      - name: Unzip 
        run: |
          tar -xzf temp_dir/btp-cli-linux-amd64-2.97.0.tar.gz -C temp_dir/

      - name: Check unzip status
        run: |
          cd temp_dir
          ls
          cd linux-amd64
          ls

      - name: Check BTP status
        run: btp --version
